"""Regenerate ar/index.html from index.html. Run from C:/Users/Настя/Desktop/клод/"""
import os, re

with open('index.html', 'r', encoding='utf-8') as f:
    src = f.read()

# ── 1. PATH FIXES ──────────────────────────────────────────────────────────
def fix_paths(h):
    h = re.sub(r'(href|src)="(index\.css|mobile-nav\.js)', r'\1="../\2', h)
    h = re.sub(r'(src|href)="assets/', r'\1="../assets/', h)
    for p in ['residencies','pricing','gallery','construction','blog','faq',
              'agents','contact','about','aldabra-giant-tortoises-seychelles',
              'baie-lazare-beach-seychelles','buying-property-in-seychelles',
              'freehold-property-seychelles','kensington-construction-seychelles',
              'phase-i-construction-update','seychelles-island-lifestyle',
              'seychelles-residency-by-investment']:
        h = h.replace(f'href="{p}.html"', f'href="../{p}.html"')
    h = re.sub(r'href="index\.html"', 'href="../"', h)
    return h

# ── 2. META + RTL ──────────────────────────────────────────────────────────
def fix_meta(h):
    h = h.replace('<html lang="en">', '<html lang="ar" dir="rtl">')
    h = h.replace('<title>Luxury Villas for Sale in Seychelles | Empathia Village Baie Lazare</title>',
                  '<title>فلل فاخرة للبيع في جزر سيشيل | Empathia Village Baie Lazare</title>')
    h = h.replace('content="https://empathia-seychelles.com/"','content="https://empathia-seychelles.com/ar/"')
    h = re.sub(r'(<link rel="canonical" href=")[^"]+(")', r'\1https://empathia-seychelles.com/ar/\2', h)
    h = h.replace('<link rel="alternate" hreflang="en" href="https://empathia-seychelles.com/ar/">',
                  '<link rel="alternate" hreflang="en" href="https://empathia-seychelles.com/">')
    h = h.replace('<link rel="alternate" hreflang="x-default" href="https://empathia-seychelles.com/ar/">',
                  '<link rel="alternate" hreflang="x-default" href="https://empathia-seychelles.com/">')
    h = h.replace(
        'content="Luxury freehold villas for sale in Baie Lazare, Seychelles. Private gated community between Four Seasons &amp; Kempinski — 35 private plots from 600 m², villas from $800,000. Staged payments. Agent programme from 3%."',
        'content="فلل فاخرة بملكية حرة للبيع في Baie Lazare، جزر سيشيل. مجمع خاص بين Four Seasons و Kempinski — 35 قطعة من 600 م²، فلل تبدأ من $800,000. دفعات متدرجة."')
    h = h.replace(
        'content="Luxury freehold villas for sale in Baie Lazare, Seychelles. 35 private plots from 600 m², villas from $800,000. Between Four Seasons &amp; Kempinski. Staged payments. Agent programme from 3%."',
        'content="فلل فاخرة بملكية حرة في Baie Lazare، سيشيل. 35 قطعة من 600 م²، فلل تبدأ من $800,000. بين Four Seasons و Kempinski."')
    h = h.replace(
        'content="Luxury Villas for Sale in Seychelles | Empathia Village Baie Lazare"',
        'content="فلل فاخرة للبيع في جزر سيشيل | Empathia Village"')
    h = h.replace(
        'name="keywords" content="luxury villas Seychelles, property for sale Seychelles, Baie Lazare villas, freehold property Seychelles, Empathia Village, villas Mahe Seychelles, Seychelles real estate investment, luxury villa rental Seychelles"',
        'name="keywords" content="فلل فاخرة سيشيل، عقارات سيشيل، فلل Baie Lazare، ملكية حرة سيشيل، Empathia Village، استثمار عقاري سيشيل"')
    h = h.replace(
        '"description": "Private luxury villa residences on Mahé, Seychelles. Baie Lazare, between Four Seasons and Kempinski. Freehold villas from $800,000."',
        '"description": "فلل فاخرة في ماهيه، سيشيل. Baie Lazare، بين Four Seasons و Kempinski. ملكية حرة تبدأ من $800,000."')
    h = h.replace('"availableLanguage": ["English"]', '"availableLanguage": ["Arabic"]')
    # Insert RTL styles + Arabic font before </head>
    rtl = '''<style id="rtl-overrides">
body{direction:rtl;text-align:right}
.nav-links{flex-direction:row-reverse}
.hero-content{text-align:right}
.hero-actions{justify-content:flex-start}
.feat-strip{flex-direction:row-reverse}
.faq-q{flex-direction:row-reverse}
.inv-num{margin-right:0;margin-left:24px}
.loc-roman{margin-right:0;margin-left:20px}
</style>
<link rel="preload" href="https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic:wght@400;500;600;700&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
<noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic:wght@400;500;600;700&display=swap"></noscript>
<style>body,p,div,span,button,input,select,a{font-family:'Noto Naskh Arabic',var(--sans),sans-serif}
h1,h2,h3,.hero-h1{font-family:'Noto Naskh Arabic',var(--serif),serif}
</style>'''
    h = h.replace('</head>', rtl + '\n</head>')
    return h

# ── 3. LANG SWITCHER ───────────────────────────────────────────────────────
SWITCHER_AR = '''<div style="display:flex;gap:8px;align-items:center;font-size:9px;letter-spacing:.12em;margin-right:16px">
      <a href="../" style="color:rgba(255,255,255,.4);text-decoration:none" title="English">EN</a>
      <span style="color:rgba(255,255,255,.2)">|</span>
      <a href="../fr/" style="color:rgba(255,255,255,.4);text-decoration:none" title="Français">FR</a>
      <span style="color:rgba(255,255,255,.2)">|</span>
      <a href="../ar/" style="color:var(--gold);text-decoration:none;font-weight:600" title="العربية">AR</a>
    </div>
    <div class="nav-actions">'''

def add_switcher(h):
    return h.replace('<div class="nav-actions">', SWITCHER_AR, 1)

# ── 4. TRANSLATIONS — longest first ───────────────────────────────────────
PAIRS = [
  # Long paragraphs
  ("Kensington Construction &amp; Development presents a gated community of luxury villas on Mahé island — positioned at Baie Lazare beach, between the legendary Four Seasons Resort Seychelles and Kempinski Seychelles Resort.",
   "تقدم Kensington Construction &amp; Development مجمعاً سكنياً مغلقاً من الفلل الفاخرة في جزيرة ماهيه — في شاطئ Baie Lazare، بين الأسطوريين Four Seasons Resort Seychelles و Kempinski Seychelles Resort."),
  ("The estate occupies elevated terrain at 50–100 metres above sea level. The terraced layout ensures most residences command uninterrupted panoramas of the Indian Ocean and tropical sunsets.",
   "يحتل المجمع أرضاً مرتفعة على 50–100 متر فوق مستوى البحر. يضمن التخطيط المدرج أن تحظى معظم المساكن بمناظر بانورامية لا تنقطع على المحيط الهندي وغروب الشمس الاستوائي."),
  ("Few destinations in the world offer the rare combination of natural beauty, political stability and genuine scarcity of premium land. Seychelles is one of them.",
   "قليلة هي الوجهات في العالم التي تجمع بين الجمال الطبيعي والاستقرار السياسي وشح الأراضي الراقية. سيشيل إحداها."),
  ("Seychelles is an archipelago of 115 islands covering just 459 km². Developable oceanfront land is finite and irreplaceable — once acquired, it does not return to the market.",
   "سيشيل أرخبيل من 115 جزيرة تمتد على 459 كم² فقط. الأراضي المطلة على البحر القابلة للتطوير محدودة ولا يمكن استبدالها — بمجرد شرائها لا تعود إلى السوق."),
  ("Specific tax implications depend on the buyer's structure and should be confirmed with qualified advisors. One of the most stable property markets in the Indian Ocean region.",
   "التداعيات الضريبية تعتمد على هيكل المشتري ويجب تأكيدها مع مستشارين مؤهلين. أحد أكثر أسواق العقارات استقراراً في منطقة المحيط الهندي."),
  ("Year-round demand from European, Middle Eastern and Asian high-net-worth buyers.",
   "طلب على مدار العام من المشترين الأثرياء الأوروبيين والشرق أوسطيين والآسيويين."),
  ("Seychelles is one of the world's foremost luxury travel and lifestyle destinations.",
   "سيشيل إحدى أبرز وجهات السفر الفاخر وأسلوب الحياة في العالم."),
  ("Rare freehold title opportunities available to international buyers, subject to applicable approvals and transaction procedures confirmed individually with the legal team.",
   "فرص نادرة لسند الملكية الحرة متاحة للمشترين الدوليين، رهناً بالموافقات المعمول بها وإجراءات المعاملات المؤكدة فردياً مع الفريق القانوني."),
  ("Strong year-round demand for luxury villa rentals. Professional management available, allowing owners to generate income when the property is not in personal use.",
   "طلب قوي على مدار العام لإيجار الفلل الفاخرة. إدارة احترافية متاحة، تسمح للملاك بتحقيق دخل في غياب الاستخدام الشخصي."),
  ("Strong year-round demand for premium villa rental with professional management options",
   "طلب قوي على مدار العام لإيجار الفلل الراقية مع خيارات الإدارة الاحترافية"),
  ("Turquoise lagoons, tropical rainforest, world-class resorts and a pace of life that cannot be replicated.",
   "بحيرات فيروزية وغابات استوائية ومنتجعات عالمية ووتيرة حياة لا مثيل لها."),
  ("Seychelles is not just an investment — it is a complete way of living.",
   "سيشيل ليست مجرد استثمار — بل هي أسلوب حياة متكامل."),
  # Villas
  ("An elegant single-storey residence designed for seamless indoor-outdoor living. Panoramic glazing, master suite with dressing room, open-plan living and dining, private pool and sun terrace. The project can be individually tailored to client requirements.",
   "مسكن أنيق من طابق واحد مصمم لحياة سلسة بين الداخل والخارج. زجاج بانورامي وجناح رئيسي مع غرفة ملابس وغرفة معيشة وطعام مفتوحة ومسبح خاص وتراس شمسي. يمكن تخصيص المشروع وفق متطلبات العميل."),
  ("The flagship two-storey residence featuring wide panoramic balconies, terraces of 150 m² and a grand private pool. The finest residence in the collection — commanding unobstructed views of the Indian Ocean. Can be expanded up to 450 m².",
   "المسكن الرئيسي من طابقين يتميز بشرفات بانورامية واسعة وتراسات 150 م² ومسبح خاص فخم. أرقى مسكن في المجموعة — بإطلالات خالية على المحيط الهندي. يمكن توسيعه حتى 450 م²."),
  ("A refined single-storey residence with panoramic glazing framing views of the tropical landscape and the Indian Ocean. The most accessible entry point to the Empathia Village collection. Plot from 600 m². Design can be extended and adapted.",
   "مسكن راقٍ من طابق واحد مع زجاج بانورامي يؤطر مناظر المشهد الاستوائي والمحيط الهندي. نقطة الدخول الأكثر إتاحةً في مجموعة Empathia Village. قطعة من 600 م². يمكن تمديد التصميم وتكييفه."),
  ("Each residence is conceived for maximum privacy, panoramic views and effortless tropical living. Private pools, generous terraces and natural materials throughout.",
   "كل مسكن مُصمَّم لأقصى قدر من الخصوصية والإطلالات البانورامية والحياة الاستوائية بلا عناء. مسابح خاصة وتراسات فسيحة ومواد طبيعية في كل مكان."),
  # Pricing
  ("Three residences. Each priced to reflect plot size, design and ocean view. All prices include land, construction, finishing and landscaping. All plots are at least 600 m².",
   "ثلاثة مساكن. كل منها بسعر يعكس حجم القطعة والتصميم والإطلالة البحرية. تشمل جميع الأسعار الأرض والبناء والتشطيب وتنسيق الحدائق. جميع القطع 600 م² على الأقل."),
  ("Each residence can be individually tailored to client requirements. We offer the possibility to increase the house area, expand the plot, adapt the floor plan, or refine the design in accordance with your personal vision. All plots are a minimum of 600 m². Please contact us to discuss your requirements.",
   "يمكن تخصيص كل مسكن فردياً وفق متطلبات العميل. نوفر إمكانية زيادة مساحة المنزل وتوسيع القطعة وتكييف المخطط أو تحسين التصميم وفق رؤيتك الشخصية. جميع القطع 600 م² كحد أدنى."),
  # What's included
  ("Every Empathia Village villa is delivered turnkey — land, construction, finishing, pool and landscaping are all included in the stated price. The following table clarifies exactly what is and is not part of the base price.",
   "كل فيلا في Empathia Village تُسلَّم جاهزة للسكن — الأرض والبناء والتشطيب والمسبح وتنسيق الحدائق مشمولة في السعر المحدد. الجدول التالي يوضح بالضبط ما هو مشمول وما هو غير مشمول."),
  ("Furniture packages are available through our partner design studios in Dubai, Europe and Asia upon request. All optional extras are priced and agreed separately from the villa purchase price. Contact us for a full itemised quotation.",
   "حزم الأثاث متاحة عبر استوديوهات التصميم الشريكة في دبي وأوروبا وآسيا عند الطلب. جميع الإضافات الاختيارية تُسعَّر وتُتفق عليها بشكل منفصل عن سعر شراء الفيلا."),
  # Interiors
  ("Each villa is delivered turnkey — premium flooring, fitted kitchens, bathroom finishing and all built-in elements included in price. Full furniture packages available through our partner design studios.",
   "كل فيلا تُسلَّم جاهزة للسكن — أرضيات فاخرة ومطابخ مجهزة وتشطيب حمامات وجميع العناصر المدمجة مشمولة في السعر. حزم أثاث كاملة متاحة عبر استوديوهات التصميم الشريكة."),
  ("Villa delivered move-in ready. All surfaces, floors and built-in elements included in price.",
   "فيلا مُسلَّمة جاهزة للسكن. جميع الأسطح والأرضيات والعناصر المدمجة مشمولة في السعر."),
  ("Natural stone, hardwood, premium tiles and bespoke joinery throughout every residence.",
   "حجر طبيعي وخشب صلب وبلاط فاخر ونجارة مخصصة في كل مسكن."),
  ("Full furniture packages available through partner design studios upon request.",
   "حزم أثاث كاملة متاحة عبر استوديوهات التصميم الشريكة عند الطلب."),
  # Lifestyle
  ("Owning a villa at Empathia Village opens up a complete Seychelles lifestyle. We assist our owners with everything — from yacht charters and car imports to island experiences and concierge services.",
   "امتلاك فيلا في Empathia Village يفتح أسلوب حياة سيشيل الكامل. نساعد ملاكنا في كل شيء — من استئجار اليخوت واستيراد السيارات إلى تجارب الجزيرة وخدمات الكونسيرج."),
  ("From sourcing and importing your vehicle to arranging yacht charters, powerboat purchases and custom car deliveries — our team handles it all.",
   "من توريد مركبتك واستيرادها إلى ترتيب استئجار اليخوت وشراء الزوارق السريعة وتسليم السيارات المخصصة — فريقنا يتولى كل شيء."),
  ("We assist our owners with the complete logistics of island living.",
   "نساعد ملاكنا بالخدمات اللوجستية الكاملة للحياة في الجزيرة."),
  # Investment
  ("Seychelles is one of the world's most constrained luxury real estate markets. Oceanfront land is finite — once gone, it cannot be replaced",
   "سيشيل من أكثر أسواق العقارات الفاخرة تقييداً في العالم. أراضي الواجهة البحرية محدودة — بمجرد بيعها لا يمكن استبدالها"),
  ("Land values in Seychelles have risen consistently, driven by limited supply and sustained international demand from HNWIs",
   "ارتفعت قيم الأراضي في سيشيل باستمرار، مدفوعةً بمحدودية العرض والطلب الدولي المستدام من أصحاب الثروات"),
  ("Foreign buyers may acquire freehold title to both villa and land, subject to applicable approvals. Purchase structure confirmed individually with the developer's legal team",
   "يحق للمشترين الأجانب الحصول على سند الملكية الحرة للفيلا والأرض، رهناً بالموافقات المعمول بها. هيكل الشراء يُؤكَّد فردياً مع الفريق القانوني للمطور"),
  ("The estate is intentionally limited to 35 residences to preserve privacy, exclusivity and long-term value appreciation for all owners",
   "المجمع محدود عمداً بـ35 مسكناً للحفاظ على الخصوصية والحصرية وارتفاع القيمة على المدى الطويل لجميع الملاك"),
  ("Residence options may be available to eligible purchasers under Seychelles regulations. Stable, tax-efficient jurisdiction. Details confirmed individually during the transaction process",
   "قد تكون خيارات الإقامة متاحة للمشترين المؤهلين وفق لوائح سيشيل. ولاية قضائية مستقرة وفعّالة ضريبياً. التفاصيل تُؤكَّد فردياً خلال عملية المعاملة"),
  # Rental
  ("Baie Lazare, adjacent to Four Seasons and Kempinski, is among the most desirable villa rental locations in the Indian Ocean.",
   "Baie Lazare، المجاور لـFour Seasons وKempinski، من أكثر مواقع إيجار الفلل استحساناً في المحيط الهندي."),
  ("Luxury villa rentals in this area command premium nightly rates from international travellers, honeymooners and high-net-worth guests.",
   "تجتذب إيجارات الفلل الفاخرة في هذه المنطقة أسعاراً ليلية متميزة من المسافرين الدوليين وأزواج شهر العسل والضيوف الأثرياء."),
  ("Baie Lazare is one of Seychelles' most prestigious coastal addresses, adjacent to Four Seasons and Kempinski.",
   "Baie Lazare من أرقى العناوين الساحلية في سيشيل، المجاور لـFour Seasons وKempinski."),
  ("2-bedroom private villa · pool · ocean views. Indicative rate based on comparable luxury properties in Baie Lazare.",
   "فيلا خاصة بغرفتي نوم · مسبح · إطلالات بحرية. سعر مؤشري مبني على عقارات فاخرة مماثلة في Baie Lazare."),
  ("3-bedroom villa · private pool · panoramic ocean view. Indicative rate based on comparable luxury properties in the region.",
   "فيلا بـ3 غرف نوم · مسبح خاص · إطلالة بانورامية على المحيط. سعر مؤشري مبني على عقارات فاخرة مماثلة في المنطقة."),
  ("4-bedroom flagship villa · 150 m² terrace · pool. Flagship residence with highest indicative rental potential.",
   "فيلا رئيسية بـ4 غرف نوم · تراس 150 م² · مسبح. المسكن الرئيسي بأعلى إمكانية إيجارية مؤشرية."),
  ("Seychelles enjoys consistent demand across all seasons, with peak periods in December–January and July–August.",
   "تتمتع سيشيل بطلب ثابت عبر جميع الفصول، مع ذروات في ديسمبر–يناير ويوليو–أغسطس."),
  ("Rental management services available through specialist partners — from guest relations to housekeeping and booking platforms.",
   "خدمات إدارة الإيجار متاحة عبر شركاء متخصصين — من علاقات الضيوف إلى التدبير المنزلي ومنصات الحجز."),
  ("Rental is entirely at the owner's discretion. Block out personal stays at any time. No compulsory rental programme.",
   "الإيجار بالكامل حسب تقدير المالك. يمكن حجب أوقات الإقامة الشخصية في أي وقت. لا يوجد برنامج إيجار إلزامي."),
  ("All rental rate figures shown above are indicative only and based on comparable luxury villa properties in the Baie Lazare / Mahé region as of 2026. Actual rental income depends on occupancy rates, management quality, market conditions, seasonality and the owner's individual preferences. No guaranteed return on investment is implied, stated or offered. Prospective purchasers should conduct their own due diligence.",
   "جميع أرقام معدلات الإيجار المذكورة أعلاه مؤشرية فقط ومبنية على عقارات فلل فاخرة مماثلة في منطقة Baie Lazare / ماهيه اعتباراً من 2026. يعتمد دخل الإيجار الفعلي على معدلات الإشغال وجودة الإدارة وظروف السوق والموسمية وتفضيلات المالك. لا يُعرض أي عائد مضمون على الاستثمار."),
  # Booking
  ("Acquiring a villa at Empathia Village is a straightforward, fully supported process. Our team guides you from initial enquiry through to construction handover — in six clear steps.",
   "الحصول على فيلا في Empathia Village عملية مباشرة ومدعومة بالكامل. يرشدك فريقنا من الاستفسار الأولي حتى تسليم البناء — في ست خطوات واضحة."),
  ("Complete the enquiry form or contact us directly via WhatsApp, email or phone. No obligation at this stage.",
   "أكمل نموذج الاستفسار أو تواصل معنا مباشرةً عبر واتساب أو البريد الإلكتروني أو الهاتف. لا التزام في هذه المرحلة."),
  ("We send you the complete villa pack within 24 hours — plans, pricing, plot availability, investment overview and agent terms.",
   "نرسل لك الحزمة الكاملة للفيلا خلال 24 ساعة — المخططات والأسعار وتوفر القطع ونظرة عامة على الاستثمار وشروط الوكيل."),
  ("Choose your preferred plot number and villa design. Individual customisation options, plot size and orientation discussed at this stage. Plot numbers and availability confirmed on request.",
   "اختر رقم القطعة المفضل وتصميم الفيلا. يُناقش في هذه المرحلة خيارات التخصيص الفردية وحجم القطعة والاتجاه. أرقام القطع والتوفر تُؤكَّد عند الطلب."),
  ("Sign a Letter of Intent to reserve your chosen plot. A reservation deposit is required to secure the plot. The LOI sets out the key terms of the transaction.",
   "وقّع خطاب نية لحجز قطعتك المختارة. يُطلب إيداع حجز لتأمين القطعة. تُحدد LOI الشروط الرئيسية للصفقة."),
  ("A payment schedule aligned with construction milestones is confirmed and agreed. Payments accepted in USD, EUR or GBP. Specific payment stages and percentages are confirmed individually upon request.",
   "يُؤكَّد ويُتفق على جدول دفع متوافق مع معالم البناء. الدفعات مقبولة بالدولار الأمريكي أو اليورو أو الجنيه الإسترليني. مراحل الدفع تُؤكَّد فردياً عند الطلب."),
  ("Kensington Construction &amp; Development begins your villa. Estimated build time is approximately 12 months per residence. Regular progress updates provided throughout.",
   "تبدأ Kensington Construction &amp; Development بناء فيلتك. وقت البناء المقدر حوالي 12 شهراً لكل مسكن. تُقدَّم تحديثات منتظمة للتقدم طوال المشروع."),
  # Construction
  ("Every villa at Empathia Village is built directly on Mahé's natural terrain — no reclaimed land, no artificial foundations. Granite bedrock, tropical hillside and Indian Ocean views from every construction milestone.",
   "كل فيلا في Empathia Village مبنية مباشرةً على الأرض الطبيعية لماهيه — لا أراضي مستردة ولا أساسات اصطناعية. قاعدة صخر غرانيتية وتلة استوائية وإطلالات على المحيط الهندي من كل معلم بناء."),
  # Masterplan
  ("The estate is designed as a private gated community of 35 individually numbered plots ranging from 600 to 2,000 m².",
   "صُمِّم المجمع كمجتمع سكني خاص مسوَّر من 35 قطعة مرقمة فردياً تتراوح من 600 إلى 2,000 م²."),
  ("Architecture integrates seamlessly with the tropical landscape — villas are positioned to maximise privacy, ocean views and natural ventilation.",
   "تندمج العمارة بسلاسة مع المشهد الاستوائي — الفلل موضوعة لتعظيم الخصوصية والإطلالات البحرية والتهوية الطبيعية."),
  ("Each villa is built to a carefully considered design by Kensington Construction &amp; Development, incorporating tropical luxury architecture, panoramic glazing, natural materials and private pools.",
   "كل فيلا مبنية وفق تصميم مدروس بعناية من Kensington Construction &amp; Development، يشمل عمارة الفخامة الاستوائية والزجاج البانورامي والمواد الطبيعية والمسابح الخاصة."),
  ("<strong style=\"color:rgba(255,255,255,.8);font-weight:500\">Plot numbers &amp; availability:</strong> All 35 plots are individually numbered. A full plot map with numbers, sizes, orientations and current availability is included in our presentation pack — sent to qualified enquiries within 24 hours.",
   "<strong style=\"color:rgba(255,255,255,.8);font-weight:500\">أرقام القطع والتوفر:</strong> جميع القطع الـ35 مرقمة فردياً. خريطة قطع كاملة بالأرقام والمساحات والاتجاهات والتوفر الحالي مشمولة في دossier العرض — تُرسَل للاستفسارات المؤهلة خلال 24 ساعة."),
  # Location
  ("White sand, turquoise water and granite boulders. One of the island's most celebrated beaches — within walking distance",
   "رمال بيضاء ومياه فيروزية وصخور غرانيتية. إحدى أشهر شواطئ الجزيرة — على مسافة المشي"),
  ("The estate shares a boundary with Kempinski Seychelles Resort. Premium location with direct access to resort-level amenities and services",
   "يتشارك المجمع حدوداً مع Kempinski Seychelles Resort. موقع متميز مع وصول مباشر إلى مرافق وخدمات على مستوى المنتجع"),
  ("Direct flights from Europe, the Middle East and Asia. Private transfers arranged on request",
   "رحلات مباشرة من أوروبا والشرق الأوسط وآسيا. نقل خاص بترتيب مسبق"),
  ("Situated 50–100 metres above sea level on terraced terrain. Most residences enjoy unobstructed views of the Indian Ocean",
   "يقع على ارتفاع 50–100 متر فوق مستوى البحر في تضاريس مدرجة. تتمتع معظم المساكن بإطلالات خالية على المحيط الهندي"),
  ("British Catholic mission with hospital and school directly opposite the estate. Children of residents are eligible to attend",
   "بعثة كاثوليكية بريطانية مع مستشفى ومدرسة مقابل المجمع مباشرةً. أطفال السكان مؤهلون للالتحاق بها"),
  ("World-class dining and resort amenities within five minutes.",
   "مطاعم عالمية المستوى ومرافق منتجع على بُعد خمس دقائق."),
  # Agents
  ("Empathia Village offers a premium product for international real estate agents, brokers and investment advisors. We welcome both direct agent registrations and co-brokerage arrangements with established firms worldwide.",
   "Empathia Village يقدم منتجاً متميزاً للوكلاء العقاريين الدوليين والوسطاء ومستشاري الاستثمار. نرحب بتسجيلات الوكلاء المباشرة وترتيبات الوساطة المشتركة مع الشركات العريقة في جميع أنحاء العالم."),
  ("Contact us by email or WhatsApp, introduce yourself and your agency, and we will send you the full Agent Pack within 24 hours. No formal registration or exclusivity required to begin.",
   "تواصل معنا عبر البريد الإلكتروني أو واتساب، عرّف بنفسك ووكالتك، وسنرسل لك الحزمة الكاملة للوكيل خلال 24 ساعة. لا يلزم تسجيل رسمي أو حصرية للبدء."),
  ("Commission from 3% of transaction value (minimum $24,000 per villa)",
   "عمولة من 3٪ من قيمة الصفقة (بحد أدنى $24,000 لكل فيلا)"),
  ("Full branded sales kit — presentations, villa sheets, floor plans",
   "مجموعة مبيعات كاملة — عروض تقديمية وكتيبات فيلا ومخططات"),
  ("Current price lists and plot availability maps", "قوائم الأسعار الحالية وخرائط توفر القطع"),
  ("Co-brokerage and referral arrangements welcome", "ترتيبات الوساطة المشتركة والإحالة مرحب بها"),
  ("Dedicated support throughout the client's purchase journey", "دعم مخصص طوال رحلة شراء العميل"),
  ("Private site visits and client consultation assistance", "زيارات موقع خاصة ومساعدة في استشارة العملاء"),
  ("No exclusivity required — open to global agents", "لا حصرية مطلوبة — مفتوح للوكلاء العالميين"),
  ("Full villa presentation deck (PDF &amp; print-ready)", "مجموعة عرض الفيلا الكاملة (PDF وجاهزة للطباعة)"),
  ("Floor plans &amp; architectural renders per villa", "مخططات وتصورات معمارية لكل فيلا"),
  ("Current pricing &amp; plot availability (confidential)", "الأسعار الحالية وتوفر القطع (سري)"),
  ("Investment overview &amp; location factsheet", "نظرة عامة على الاستثمار وورقة بيانات الموقع"),
  ("Direct developer contact for client Q&amp;A", "تواصل مباشر مع المطور لأسئلة العملاء"),
  # VS Eden
  ("Two premium addresses in Seychelles — each suited to a different lifestyle and vision. Understanding the difference helps buyers make the right choice.",
   "عنوانان متميزان في سيشيل — كل منهما يناسب أسلوب حياة ورؤية مختلفة. فهم الفرق يساعد المشترين على اتخاذ الخيار الصحيح."),
  ("Natural hillside terrain — no reclaimed land", "تضاريس تلال طبيعية — لا أراضي مستردة"),
  ("Private villa plots from 600 m²", "قطع فيلا خاصة من 600 م²"),
  ("Unobstructed Indian Ocean views", "إطلالات خالية على المحيط الهندي"),
  ("Immersive tropical landscape", "مشهد استوائي غامر"),
  ("Gated residential community · 35 plots", "مجتمع سكني مسوَّر · 35 قطعة"),
  ("Individual design customisation available", "التخصيص الفردي للتصميم متاح"),
  ("Quiet, private south Mahé setting", "بيئة هادئة وخاصة في جنوب ماهيه"),
  ("Marina and waterfront setting", "بيئة مارينا وواجهة مائية"),
  ("Apartment and townhouse format", "شقق ومنازل تاون هاوس"),
  ("Reclaimed island setting", "جزيرة مستردة"),
  ("Closer to Victoria and city infrastructure", "أقرب إلى فيكتوريا والبنية التحتية الحضرية"),
  ("More urban and resort-style atmosphere", "أجواء أكثر حضرية وعلى طراز المنتجع"),
  ("Eden Island is a well-established destination for buyers seeking a marina-facing apartment or townhouse lifestyle closer to Victoria.",
   "Eden Island وجهة راسخة للمشترين الباحثين عن شقق أو تاون هاوس تطل على المارينا، أقرب إلى فيكتوريا."),
  ("Empathia Village is designed for buyers seeking privacy, nature, larger private plots and a quieter villa lifestyle — in one of Mahé's most prestigious coastal addresses, between Four Seasons and Kempinski.",
   "Empathia Village مصمم للمشترين الباحثين عن الخصوصية والطبيعة وقطع خاصة أكبر وأسلوب حياة فيلا أكثر هدوءاً — في أحد أرقى العناوين الساحلية في ماهيه، بين Four Seasons وKempinski."),
  # FAQ long answers
  ("No. Empathia Village does not offer, imply or guarantee citizenship, a passport or any immigration status. Residence options (not citizenship) may be available to eligible purchasers under Seychelles regulations, subject to individual eligibility review and applicable procedures. We strongly recommend consulting with a qualified Seychelles immigration lawyer for precise and current advice on residency requirements.",
   "لا. Empathia Village لا يقدم ولا يضمن الجنسية أو جواز السفر أو أي وضع هجرة. قد تكون خيارات الإقامة (لا الجنسية) متاحة للمشترين المؤهلين وفق لوائح سيشيل. نوصي بشدة باستشارة محامٍ مؤهل في قانون الهجرة بسيشيل."),
  ("Simply contact us by email at info@empathia-seychelles.com or via WhatsApp +248 271 51 02 to introduce yourself and your agency. We will send you the full Agent Pack — including villa presentations, floor plans, pricing and commission terms — within 24 hours. No formal registration or exclusivity agreement is required to begin. Commission starts from 3% of transaction value, with a minimum of $24,000 per villa transaction.",
   "تواصل معنا عبر البريد الإلكتروني info@empathia-seychelles.com أو واتساب +248 271 51 02. سنرسل لك الحزمة الكاملة للوكيل خلال 24 ساعة. لا يلزم تسجيل رسمي أو حصرية للبدء. العمولة تبدأ من 3٪ بحد أدنى $24,000 لكل صفقة."),
  ("The stated price includes: the land plot and freehold title transfer support, full villa construction, premium interior finishing (floors, walls, ceilings), fitted kitchen and bathroom suites, private pool and pool terrace, landscaping and tropical garden, driveway and parking, and connection to estate infrastructure (roads, gate, utilities). Furniture and moveable items are not included but are available as an optional package.",
   "السعر المحدد يشمل: قطعة الأرض ودعم نقل سند الملكية الحرة، بناء الفيلا الكامل، تشطيب داخلي فاخر، مطبخ مجهز وأجنحة حمامات، مسبح خاص وتراس مسبح، تنسيق حدائق وحديقة استوائية، ممر سيارات وموقف، وتوصيل ببنية تحتية المجمع. الأثاث غير مشمول لكنه متاح كحزمة اختيارية."),
  ("Yes. Full furniture packages are available as an optional add-on through our partner design studios, sourcing from Dubai, Europe and Asia. Packages are priced separately and tailored to your villa size and design preferences. Contact us to discuss options after plot selection.",
   "نعم. حزم الأثاث الكاملة متاحة كإضافة اختيارية عبر استوديوهات التصميم الشريكة من دبي وأوروبا وآسيا. الحزم مسعَّرة بشكل منفصل ومخصصة حسب حجم فيلتك. تواصل معنا لمناقشة الخيارات بعد اختيار القطعة."),
  ("Baie Lazare, adjacent to Four Seasons and Kempinski, is among the most desirable villa rental locations in the Indian Ocean. Indicative nightly rates for comparable luxury villas in this area range from approximately $2,000 to $5,000+ per night depending on villa size and season. These figures are indicative only — based on comparable properties in the region — and do not constitute a guaranteed return. Actual rental income depends on occupancy, management quality, market conditions and the owner's own decisions. No guaranteed rental income is offered.",
   "Baie Lazare المجاور لـFour Seasons وKempinski من أكثر مواقع إيجار الفلل استحساناً في المحيط الهندي. الأسعار الليلية المؤشرية للفلل الفاخرة المماثلة تتراوح من حوالي $2,000 إلى $5,000+ في الليلة. هذه الأرقام مؤشرية فقط ولا تشكل عائداً مضموناً. لا يُعرض دخل إيجار مضمون."),
  ("Payments are staged in line with construction milestones — typically reservation, foundation, structure, finishing and handover. The exact payment percentages and schedule are confirmed individually upon request. Payments are accepted in USD, EUR or GBP. No specific payment percentages are published publicly — contact us to receive the current payment plan for your chosen villa.",
   "الدفعات متدرجة وفق معالم البناء — الحجز والأساس والهيكل والتشطيب والتسليم. النسب والجدول الزمني يُؤكَّد فردياً عند الطلب. الدفعات مقبولة بالدولار أو اليورو أو الجنيه الإسترليني."),
  ("Yes. The estate has 35 numbered plots. A detailed plot map with plot numbers, areas, orientations and current availability status is included in our full presentation pack, sent to qualified buyers upon request. Plot availability changes as reservations are made, so we recommend requesting current status directly.",
   "نعم. يضم المجمع 35 قطعة مرقمة. خريطة قطع تفصيلية مشمولة في دossier العرض الكامل تُرسَل للمشترين المؤهلين عند الطلب. توفر القطع يتغير مع الحجوزات لذا نوصي بطلب الحالة الحالية مباشرة."),
  ("Yes. Each villa design can be adapted to individual requirements — including floor plan changes, area expansion, material selections, additional rooms or bespoke architectural features. Villa Georgette, for example, can be extended up to 450 m². Customisation options and associated costs are discussed individually during the sales process. Contact us to discuss your vision.",
   "نعم. يمكن تكييف كل تصميم وفق المتطلبات الفردية — تغييرات المخطط وتوسيع المساحة واختيار المواد وغرف إضافية. فيلا Georgette يمكن تمديدها حتى 450 م². تواصل معنا لمناقشة رؤيتك."),
  ("Yes. Foreign buyers may acquire freehold title to both the villa and the land on which it stands, subject to applicable approvals and transaction procedures. The purchase process is fully supported by our legal team.",
   "نعم. يحق للمشترين الأجانب الحصول على سند الملكية الحرة للفيلا والأرض التي تقع عليها، رهناً بالموافقات والإجراءات المعمول بها. عملية الشراء مدعومة بالكامل من فريقنا القانوني."),
  ("Payments are accepted in USD, EUR or GBP. Payments may be made in the Seychelles jurisdiction or internationally. A staged payment plan aligned to construction milestones is available on request.",
   "الدفعات مقبولة بالدولار الأمريكي أو اليورو أو الجنيه الإسترليني. يمكن الدفع في ولاية سيشيل القضائية أو دولياً. خطة دفع متدرجة متوافقة مع معالم البناء متاحة عند الطلب."),
  ("Each villa takes approximately 12 months to construct from groundbreaking. The full estate is planned for completion within 3 years. Phase I represents 25% of total plots and is currently under active construction.",
   "يستغرق بناء كل فيلا حوالي 12 شهراً من وضع حجر الأساس. المجمع الكامل مخطط لإتمامه خلال 3 سنوات. المرحلة الأولى تمثل 25٪ من إجمالي القطع وهي حالياً قيد البناء النشط."),
  ("Residence options may be available to eligible purchasers under Seychelles regulations. Eligibility and applicable requirements are confirmed individually with the legal team during the transaction process. We recommend consulting with a qualified Seychelles legal advisor for precise details.",
   "قد تكون خيارات الإقامة متاحة للمشترين المؤهلين وفق لوائح سيشيل. يُؤكَّد التأهيل والمتطلبات المعمول بها فردياً مع الفريق القانوني خلال عملية المعاملة. نوصي باستشارة مستشار قانوني مؤهل في سيشيل."),
  ("Yes. Owners may rent their villa on short or long-term terms. Professional villa management services are available, allowing owners to benefit from hotel-quality rental management.",
   "نعم. يحق للملاك تأجير فيلتهم بشروط قصيرة أو طويلة الأمد. خدمات إدارة الفيلا الاحترافية متاحة للاستفادة من إدارة إيجار بجودة فندقية."),
  ("Absolutely. We offer a private one-week discovery tour to the Seychelles with accommodation on Eden Island. Our team arranges all logistics, site visits and meetings. Contact us to plan your visit.",
   "بالتأكيد. نقدم جولة اكتشافية خاصة لمدة أسبوع إلى سيشيل مع إقامة في Eden Island. يرتب فريقنا كل اللوجستيات وزيارات المواقع والاجتماعات. تواصل معنا لتخطيط زيارتك."),
  # Presentation + footer
  ("Receive villa plans, pricing, location details and partnership terms. Our full presentation pack is sent directly to qualified buyers, investors and agents.",
   "احصل على مخططات الفيلا والأسعار وتفاصيل الموقع وشروط الشراكة. دossier العرض الكامل يُرسَل مباشرةً للمشترين والمستثمرين والوكلاء المؤهلين."),
  ("Villa floor plans &amp; architectural drawings", "مخططات الفيلا والرسومات المعمارية"),
  ("Pricing &amp; plot availability", "الأسعار وتوفر القطع"),
  ("Location &amp; masterplan documentation", "وثائق الموقع والمخطط العام"),
  ("Agent partnership terms", "شروط الشراكة مع الوكيل"),
  ("Get the full presentation, villa price list and availability. Our team responds within 24 hours.",
   "احصل على العرض الكامل وقائمة أسعار الفيلا والتوفر. يرد فريقنا خلال 24 ساعة."),
  ("Prices, floor plans, areas, images, purchase terms and any other information presented on this website are provided for general information purposes only and do not constitute a public offer. Current pricing, availability, specifications, payment terms and transaction procedure are confirmed individually upon request.",
   "الأسعار والمخططات والمساحات والصور وشروط الشراء وأي معلومات أخرى مقدمة على هذا الموقع لأغراض معلوماتية عامة فقط ولا تشكل عرضاً عاماً. الأسعار الحالية والتوفر والمواصفات وشروط الدفع وإجراءات المعاملة تُؤكَّد فردياً عند الطلب."),
  ("© 2026 All rights reserved · Private Living · Naturally Yours",
   "© 2026 جميع الحقوق محفوظة · معيشة خاصة · طبيعية بامتياز"),
  # News
  ("Phase I: 25% of residences reserved — construction underway",
   "المرحلة الأولى: 25٪ من المساكن محجوزة — البناء جارٍ"),
  ("Phase I is now 25% reserved. Construction of the first residences at Empathia Village is actively underway on the Mahé hillside.",
   "المرحلة الأولى الآن محجوزة بنسبة 25٪. بناء المساكن الأولى في Empathia Village جارٍ بنشاط على تلة ماهيه."),
  ("Phase II plots now available", "قطع المرحلة الثانية متاحة الآن"),
  ("Second phase plots are open for reservation. Villa Anna, Jane and Georgette designs available on plots from 600 to 2,000 m².",
   "قطع المرحلة الثانية مفتوحة للحجز. تصاميم فيلا Anna وJane وGeorgette متاحة على قطع من 600 إلى 2,000 م²."),
  # Villa specs
  ("Open-plan living &amp; dining room", "غرفة معيشة وطعام مفتوحة"),
  ("Master bedroom with dressing room", "غرفة نوم رئيسية مع غرفة ملابس"),
  ("Individual project customisation available", "التخصيص الفردي للمشروع متاح"),
  ("From $990,000. Plot from 600 m². Individual adjustments to design, size and layout available on request. Not a public offer.",
   "من $990,000. قطعة من 600 م². تعديلات فردية على التصميم والحجم والتخطيط متاحة عند الطلب. ليست عرضاً عاماً."),
  ("From $2,100,000. Plot from 1,500 m². All designs can be individually adapted. Not a public offer.",
   "من $2,100,000. قطعة من 1,500 م². جميع التصاميم يمكن تكييفها فردياً. ليست عرضاً عاماً."),
  ("Two floors with panoramic balconies", "طابقان مع شرفات بانورامية"),
  ("Individual customisation up to 450 m²", "تخصيص فردي حتى 450 م²"),
  ("Panoramic floor-to-ceiling glazing", "زجاج بانورامي من الأرض إلى السقف"),
  ("Land plot &amp; freehold title transfer support", "قطعة أرض ودعم نقل سند الملكية الحرة"),
  ("Full villa construction to completion", "بناء الفيلا الكامل حتى الانتهاء"),
  ("Premium interior finishing (flooring, walls, ceilings)", "تشطيب داخلي فاخر (أرضيات، جدران، أسقف)"),
  ("Fitted kitchens &amp; bathroom suites", "مطابخ مجهزة وأجنحة حمامات"),
  ("Landscaping, tropical garden &amp; driveway", "تنسيق الحدائق، حديقة استوائية وممر السيارات"),
  ("Estate roads, security gate &amp; shared infrastructure", "طرق المجمع وبوابة أمنية وبنية تحتية مشتركة"),
  ("Home automation &amp; smart-home systems", "أتمتة المنزل وأنظمة المنزل الذكي"),
  ("Custom design expansion (area, layout, materials)", "توسع التصميم المخصص (مساحة، تخطيط، مواد)"),
  ("Vehicle import to Mahé (car, SUV, convertible)", "استيراد مركبة إلى ماهيه (سيارة، SUV، كابريوليه)"),
  ("Yacht / catamaran charter &amp; purchase assistance", "مساعدة استئجار وشراء يخت/كتاماران"),
  ("Yacht &amp; catamaran charter and purchase assistance", "مساعدة استئجار وشراء يخت وكتاماران"),
  ("Professional short-term rental management", "إدارة إيجار قصير الأمد احترافية"),
  ("Legal &amp; residency application advisory", "استشارات قانونية وطلب إقامة"),
  ("Concierge &amp; property management services", "خدمات كونسيرج وإدارة ممتلكات"),
  ("Explore the archipelago from your doorstep", "استكشف الأرخبيل من باب منزلك"),
  ("Cabrio hire &amp; island exploration by car", "استئجار كابريوليه واستكشاف الجزيرة بالسيارة"),
  ("Full concierge, transfers and estate services", "خدمة كونسيرج كاملة، نقل وخدمات المجمع"),
  ("Powerboat, speedboat &amp; motorboat sourcing", "توريد زوارق بمحرك وزوارق سريعة"),
  ("Vehicle import &amp; customs clearance on Mahé", "استيراد مركبات وتخليص جمركي في ماهيه"),
  ("Luxury convertibles &amp; premium cars delivered to villa", "كابريوليهات فاخرة وسيارات راقية تُسلَّم إلى الفيلا"),
  ("Aldabra tortoises — icon of the Seychelles", "سلاحف ألدابرا — رمز سيشيل"),
  ("Yacht &amp; Catamaran Charter", "استئجار يخت وكتاماران"),
  ("Private pool &amp; pool terrace", "مسبح خاص وتراس مسبح"),
  ("Private pool &amp; sun terrace", "مسبح خاص وتراس شمسي"),
  ("Open-plan living &amp; dining", "معيشة وطعام مفتوح"),
  ("Master suite with dressing room", "جناح رئيسي مع غرفة ملابس"),
  ("Panoramic balconies · master suite", "شرفات بانورامية · جناح رئيسي"),
  ("Panoramic glazing · ocean views", "زجاج بانورامي · إطلالات بحرية"),
  ("Tropical garden · parking", "حديقة استوائية · موقف سيارات"),
  ("2 bedrooms · private pool", "غرفتا نوم · مسبح خاص"),
  ("4 bedrooms · private pool", "4 غرف نوم · مسبح خاص"),
  ("4 bedrooms · Master suite", "4 غرف نوم · جناح رئيسي"),
  ("2 bedrooms · Private pool", "غرفتا نوم · مسبح خاص"),
  ("Individual customisation available", "التخصيص الفردي متاح"),
  ("from 140 m² · 2 Bedrooms", "من 140 م² · غرفتا نوم"),
  ("from 240 m² · 3 Bedrooms", "من 240 م² · 3 غرف نوم"),
  ("from 350 m² · 4 Bedrooms", "من 350 م² · 4 غرف نوم"),
  ("Plot from 1,500 m² · Not a public offer", "قطعة من 1,500 م² · ليست عرضاً عاماً"),
  ("Plot from 600 m² · Not a public offer", "قطعة من 600 م² · ليست عرضاً عاماً"),
  ("12 months construction", "بناء 12 شهراً"),
  ("Terrace 150 m²", "تراس 150 م²"),
  ("months per villa", "أشهر لكل فيلا"),
  ("natural terrain", "تضاريس طبيعية"),
  ("license holder", "حامل الرخصة"),
  ("design &amp; build", "التصميم والبناء"),
  # Map
  ("Four Seasons Resort Seychelles — adjacent", "Four Seasons Resort Seychelles — مجاور"),
  ("Kempinski Seychelles Resort — shared boundary", "Kempinski Seychelles Resort — حدود مشتركة"),
  ("Baie Lazare Beach — 2 minutes on foot", "شاطئ Baie Lazare — دقيقتان سيراً"),
  ("Mahé International Airport — 30 minutes by car", "مطار ماهيه الدولي — 30 دقيقة بالسيارة"),
  ("Located between Four Seasons Resort Seychelles and Kempinski Seychelles Resort",
   "يقع بين Four Seasons Resort Seychelles و Kempinski Seychelles Resort"),
  ("Open in Google Maps", "فتح في خرائط Google"),
  # FAQ questions
  ("Can foreign nationals purchase property at Empathia Village?",
   "هل يمكن للمواطنين الأجانب شراء عقارات في Empathia Village؟"),
  ("What currencies are payments accepted in?", "ما هي العملات المقبولة للدفع؟"),
  ("How long does construction take?", "كم يستغرق وقت البناء؟"),
  ("Do I qualify for Seychelles residency?", "هل أنا مؤهل للحصول على الإقامة في سيشيل؟"),
  ("Can I rent my villa when I'm not using it?", "هل يمكنني تأجير فيلتي عندما لا أستخدمها؟"),
  ("Is an inspection visit possible before purchase?", "هل يمكن زيارة الموقع قبل الشراء؟"),
  ("What exactly is included in the villa price?", "ما الذي يشمله سعر الفيلا بالضبط؟"),
  ("Are furniture packages available?", "هل تتوفر حزم الأثاث؟"),
  ("What is the short-term rental potential?", "ما هي إمكانية الإيجار قصير الأمد؟"),
  ("What is the payment plan?", "ما هي خطة الدفع؟"),
  ("Can I see available plot numbers and a plot map?", "هل يمكنني رؤية أرقام القطع المتاحة وخريطة القطع؟"),
  ("Can I customise the villa design?", "هل يمكنني تخصيص تصميم الفيلا؟"),
  ("Do you offer citizenship by investment or a passport programme?",
   "هل تقدمون جنسية بالاستثمار أو برنامج جواز سفر؟"),
  ("I am a real estate agent — how do I register?", "أنا وكيل عقاري — كيف أسجل؟"),
  # Nav — HTML context to avoid collisions
  (">Home<", ">الرئيسية<"),
  (">Residencies<", ">المساكن<"),
  (">Pricing<", ">الأسعار<"),
  (">Gallery<", ">المعرض<"),
  (">Construction<", ">البناء<"),
  (">Agents<", ">الوكلاء<"),
  (">Contacts<", ">اتصل بنا<"),
  (">FAQ<", ">الأسئلة الشائعة<"),
  (">BLOG<", ">مدونة<"),
  # Form
  (">I am a… Buyer / Investor / Agent / Partner<", ">أنا... مشترٍ / مستثمر / وكيل / شريك<"),
  (">Buyer<", ">مشترٍ<"),
  (">Investor<", ">مستثمر<"),
  (">Agent<", ">وكيل<"),
  (">Partner<", ">شريك<"),
  (">I am a…<", ">أنا...<"),
  ("Your name", "اسمك"),
  ("Email address", "عنوان البريد الإلكتروني"),
  ("WhatsApp / Phone", "واتساب / الهاتف"),
  ("Send Request", "إرسال الطلب"),
  # Short UI
  ("Request Full Presentation", "طلب العرض الكامل"),
  ("View Residences", "استعراض المساكن"),
  ("Arrange a Private Visit", "ترتيب زيارة خاصة"),
  ("Reserve Your Residence", "احجز مسكنك"),
  ("Request plot map →", "طلب خريطة القطع →"),
  ("Request Presentation", "طلب العرض"),
  ("Request Agent Pack", "طلب حقيبة الوكيل"),
  ("View Full Agent Programme", "عرض برنامج الوكيل الكامل"),
  ("Enquire About Empathia Village", "الاستفسار عن Empathia Village"),
  ("Enquire About Services", "الاستفسار عن الخدمات"),
  ("Begin Your Enquiry", "ابدأ استفساركم"),
  ("WhatsApp Us Now", "تواصل معنا عبر واتساب"),
  ("Contact via WhatsApp", "التواصل عبر واتساب"),
  ("Private Enquiry", "استفسار خاص"),
  ("Request Price List", "طلب قائمة الأسعار"),
  ("Get Villa Price List", "الحصول على قائمة أسعار الفيلا"),
  ("View Details", "عرض التفاصيل"),
  ("All Residences", "جميع المساكن"),
  ("Freehold Title", "ملكية حرة"),
  ("Staged Payments", "دفعات متدرجة"),
  ("Rental Potential", "إمكانية الإيجار"),
  ("Restricted Supply", "عرض محدود"),
  ("Consistent Value Growth", "نمو ثابت في القيمة"),
  ("Premium Rental Yield", "عائد إيجاري متميز"),
  ("Seychelles Residency", "إقامة سيشيل"),
  ("Only 35 Plots Available", "35 قطعة فقط متاحة"),
  ("Freehold for Foreign Nationals", "ملكية حرة للمواطنين الأجانب"),
  ("The Proposition", "العرض"),
  ("Project Completion", "اكتمال المشروع"),
  ("Exclusive Plots", "قطع حصرية"),
  ("Entry Price", "سعر الدخول"),
  ("Phase I Reserved", "المرحلة الأولى محجوزة"),
  ("Full Completion", "الاكتمال الكامل"),
  ("Phase I Active", "المرحلة الأولى نشطة"),
  ("Site Preparation", "تجهيز الموقع"),
  ("Total Plots", "إجمالي القطع"),
  ("m² per Plot", "م² لكل قطعة"),
  ("Estate Masterplan · 2026", "المخطط العام للمجمع · 2026"),
  ("Included in Price", "مشمول في السعر"),
  ("Everything to Move In", "كل ما تحتاجه للانتقال"),
  ("Available as Add-On", "متاح كإضافة"),
  ("Optional Extras", "إضافات اختيارية"),
  ("Full Interior Finish", "تشطيب داخلي كامل"),
  ("Material Selection", "اختيار المواد"),
  ("Furniture Packages", "حزم الأثاث"),
  ("Agent Commission", "عمولة الوكيل"),
  ("of transaction value", "من قيمة الصفقة"),
  ("Minimum fee per transaction", "الحد الأدنى للرسوم لكل صفقة"),
  ("Starting villa price from $800,000", "سعر الفيلا يبدأ من $800,000"),
  ("What You Receive", "ما ستحصل عليه"),
  ("How to Register", "كيفية التسجيل"),
  ("Year-Round Demand", "طلب على مدار العام"),
  ("Professional Management", "إدارة احترافية"),
  ("Owner's Choice", "اختيار المالك"),
  ("per night", "في الليلة"),
  ("Detailed Documentation", "توثيق تفصيلي"),
  ("Private Consultation", "استشارة خاصة"),
  ("Request a Private Consultation", "طلب استشارة خاصة"),
  ("Photography &amp; Film", "الصور والأفلام"),
  ("Choosing Your Seychelles Address", "اختيار عنوانك في سيشيل"),
  ("Natural hillside living.<br>Privacy. Ocean views.", "حياة التلال الطبيعية.<br>الخصوصية. الإطلالات البحرية."),
  ("Marina lifestyle.<br>Urban resort atmosphere.", "أسلوب حياة المارينا.<br>أجواء المنتجع الحضري."),
  ("Project Updates", "تحديثات المشروع"),
  ("Built on Seychelles Soil", "مبني على أرض سيشيل"),
  ("Construction Progress", "تقدم البناء"),
  ("The Collection", "المجموعة"),
  ("Three Villa Designs", "ثلاثة تصاميم للفيلا"),
  ("Signature Residence", "المسكن المميز"),
  ("Architectural Project", "المشروع المعماري"),
  ("Investment Destination", "وجهة استثمارية"),
  ("Island Lifestyle", "أسلوب حياة الجزيرة"),
  ("A Rare Opportunity", "فرصة نادرة"),
  ("Partner Programme", "برنامج الشراكة"),
  ("Transparency", "الشفافية"),
  ("The Setting", "البيئة"),
  ("The Estate", "المجمع"),
  ("Masterplan", "المخطط العام"),
  ("The Finest Address<br>in Seychelles", "أرقى عنوان<br>في جزر سيشيل"),
  ("35 Private Plots<br>in Natural Terrain", "35 قطعة خاصة<br>في تضاريس طبيعية"),
  ("Crafted for Exceptional Living", "مُصمَّم لحياة استثنائية"),
  ("Yachts, Boats &amp; Automobiles", "اليخوت والقوارب والسيارات"),
  ("Life on Mahé — Beyond the Villa", "الحياة في Mahé — خارج الفيلا"),
  ("Why Seychelles?", "لماذا سيشيل؟"),
  ("What's Included &amp; What's Optional", "ما هو مشمول وما هو اختياري"),
  ("Short-Term Rental Income Potential", "إمكانية دخل الإيجار قصير الأمد"),
  ("The Reservation &amp; Booking Process", "عملية الحجز والاستفسار"),
  ("Frequently Asked Questions", "الأسئلة الشائعة"),
  ("For Agents<br>&amp; Partners", "للوكلاء<br>والشركاء"),
  ("A new standard<br>of private luxury living", "معيار جديد<br>في المعيشة الفاخرة الخاصة"),
  ("Between<br>Four Seasons<br>&amp; Kempinski", "بين<br>Four Seasons<br>و Kempinski"),
  ("Between Four Seasons &amp; Kempinski", "بين Four Seasons و Kempinski"),
  ("2 Minutes to Baie Lazare", "دقيقتان من Baie Lazare"),
  ("30 Minutes from Mahé Airport", "30 دقيقة من مطار ماهيه"),
  ("Elevated Panoramic Position", "موقع بانورامي مرتفع"),
  ("International School &amp; Medical", "مدرسة دولية ومستشفى"),
  ("Private Living · Naturally Yours", "معيشة خاصة · طبيعية بامتياز"),
  ("Freehold Title · Staged Payments · Between Four Seasons &amp; Kempinski",
   "ملكية حرة · دفعات متدرجة · بين Four Seasons و Kempinski"),
  ("35 Private Plots", "35 قطعة خاصة"),
  ("12 Months Build", "البناء 12 شهراً"),
  ("From $800,000", "تبدأ من $800,000"),
  # Cinematic
  ("Where the Indian Ocean<br>Becomes Your Garden", "حيث يصبح المحيط الهندي<br>حديقتك الخاصة"),
  ("Baie Lazare. White sand. Granite boulders. Turquoise water. Two of the world's finest resort hotels as your neighbours.",
   "Baie Lazare. رمال بيضاء. صخور غرانيتية. مياه فيروزية. اثنان من أفخر فنادق المنتجعات في العالم كجيرانك."),
  ("An address defined by its neighbours. Baie Lazare is consistently ranked among the Indian Ocean's most beautiful bays — and Empathia Village occupies its finest elevated position.",
   "عنوان تُحدده جيرانه. Baie Lazare تُصنَّف باستمرار ضمن أجمل خلجان المحيط الهندي — و Empathia Village يحتل أفضل موقع مرتفع فيها."),
  ('"Empathy is what restores a lost paradise"', '«التعاطف هو ما يُعيد الفردوس المفقود»'),
  ('"Your home by the ocean. Your private resort. Your sanctuary in the Indian Ocean."',
   '«منزلك على ضفاف المحيط. منتجعك الخاص. ملاذك في المحيط الهندي.»'),
  ("Built on Trust · Designed for Life · Class 1 License", "مبني على الثقة · مصمم للحياة · رخصة الفئة الأولى"),
  ("Kensington Construction &amp; Development · Class 1 License · Seychelles",
   "Kensington Construction &amp; Development · رخصة الفئة الأولى · سيشيل"),
  # Remaining short
  ("Land Supply", "المعروض من الأراضي"),
  ("Jurisdiction", "الولاية القضائية"),
  ("Island Lifestyle", "أسلوب حياة الجزيرة"),
  ("Scroll", "تمرير"),
  ("Developer Experience", "خبرة المطور"),
  ("Homes Delivered", "منازل مُسلَّمة"),
  ("Starting Price", "السعر الابتدائي"),
  ("Private Plots", "قطع خاصة"),
  ("To Beach", "إلى الشاطئ"),
  ("Latest", "آخر الأخبار"),
  ("Find Us", "موقعنا"),
  ("Project Location", "موقع المشروع"),
  ("Location", "الموقع"),
  ("Giant Tortoises", "السلاحف العملاقة"),
  ("Island Drives", "جولات الجزيرة"),
  ("Concierge Service", "خدمة الكونسيرج"),
  ("Residence", "مسكن"),
  ("Residency", "الإقامة"),
  ("Bedrooms", "غرف النوم"),
  ("Bathrooms", "الحمامات"),
  ("m² Area", "م² المساحة"),
  ("m² Terrace", "م² التراس"),
  ("m² Pool", "م² المسبح"),
  ("m² Plot", "م² القطعة"),
  ("Private Pool", "مسبح خاص"),
  ("All parking", "جميع مواقف السيارات"),
  ("Price includes:", "السعر يشمل:"),
  ("Name", "الاسم"),
  ("Email", "البريد الإلكتروني"),
  ("Entry-level private villa", "فيلا خاصة بسعر تنافسي"),
  ("Elegant ocean-view villa", "فيلا أنيقة بإطلالة بحرية"),
  ("Flagship residence", "المسكن الرئيسي"),
  ("Parking for 2 vehicles", "موقف لسيارتين"),
  ("Plot from", "قطعة من"),
  ("Interior concept visualization", "تصور مفهوم الديكور الداخلي"),
  ("How to Buy", "كيفية الشراء"),
  ("Express Interest", "التعبير عن الاهتمام"),
  ("Receive Full Presentation", "استلام العرض الكامل"),
  ("Select Your Plot", "اختيار قطعتك"),
  ("Letter of Intent (LOI)", "خطاب النية (LOI)"),
  ("Staged Payment Plan", "خطة الدفع المتدرجة"),
  ("Construction &amp; Handover", "البناء والتسليم"),
  ("SEYCHELLES · MAHÉ", "سيشيل · ماهيه"),
  ("Investment overview", "نظرة عامة على الاستثمار"),
  ("from 240 m²", "من 240 م²"),
  # JS
  ("'Please enter your name or contact details.'", "'يرجى إدخال اسمك أو بيانات الاتصال.'"),
  ("'Sending…'", "'جارٍ الإرسال...'"),
  ("btn.textContent = 'Send Request'", "btn.textContent = 'إرسال الطلب'"),
  ("btn.textContent = 'Request Presentation'", "btn.textContent = 'طلب العرض'"),
  ("page: 'Home'", "page: 'الرئيسية'"),
]

def apply(h, pairs):
    for old, new in pairs:
        if old in h:
            h = h.replace(old, new)
    return h

out = fix_paths(src)
out = fix_meta(out)
out = apply(out, PAIRS)
out = add_switcher(out)

os.makedirs('ar', exist_ok=True)
with open('ar/index.html', 'w', encoding='utf-8') as f:
    f.write(out)

remaining = len([m for m in __import__('re').finditer(r'>[A-Za-z]{25,}<', out)])
print(f"Done. Long English text nodes remaining: {remaining}")
